MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  PRETRAINED_DETECTOR_CKPT: "./custom_output_detector/model_final.pth"
  ROI_ATTRIBUTE_HEAD:
    NUM_ATTRIBUTES: 1
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RELATION_ON: True
  ATTRIBUTE_ON: False
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.23232838, 0.63365731, 1.28478321, 3.15089189)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_PER_BATCH: False
    RPN_MID_CHANNEL: 256
  ROI_HEADS:
    USE_FPN: True
    POSITIVE_FRACTION: 0.5
    BG_IOU_THRESHOLD: 0.3
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 11
    MLP_HEAD_DIM: 4096
  ROI_RELATION_HEAD:
    NUM_CLASSES: 4
    USE_GT_BOX: False
    USE_GT_OBJECT_LABEL: False
    REQUIRE_BOX_OVERLAP: False
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: True
    PREDICTOR: "CausalAnalysisPredictor"
    USE_RELATION_CLASS_WEIGHT: True
    RELATION_CLASS_WEIGHTS: [0.2, 1.68, 3.55, 0.47]
    CAUSAL:
      EFFECT_TYPE: "none"
      FUSION_TYPE: "sum"
      CONTEXT_LAYER: "motifs"
DATASETS:
  TRAIN: ("VG_custom_dataset_train",)
  VAL: ("VG_custom_dataset_val",)
  TEST: ("VG_custom_dataset_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0001
  STEPS: (1800, 2600)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 2
  PRE_VAL: False
  TO_VAL: False
TEST:
  IMS_PER_BATCH: 1
  ALLOW_LOAD_FROM_CACHE: False
  RELATION:
    REQUIRE_OVERLAP: False
OUTPUT_DIR: './custom_output_sgdet'
DTYPE: "float16"
GLOVE_DIR: "."
